name: Test

on:
  push:
     
jobs:
  build:
    name: RSpec
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x
    - name: Bundle
      run: |
        gem update --system --no-document 
        gem install bundler --no-document
        bundle install
    - name: Run RSpec
      run: rspec
